<?php

namespace ContainerZ47IcId;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JqkX_GMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jqkX.GM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jqkX.GM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'amenagements' => ['privates', '.errored..service_locator.jqkX.GM.App\\Entity\\Amenagements', NULL, 'Cannot autowire service ".service_locator.jqkX.GM": it references class "App\\Entity\\Amenagements" but no such service exists.'],
        ], [
            'amenagements' => 'App\\Entity\\Amenagements',
        ]);
    }
}
