<?php

namespace Container1FU6axx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAmenagements2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bIrh9qF.App\Entity\Amenagements' shared service.
     *
     * @return \App\Entity\Amenagements
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bIrh9qF": it references class "App\\Entity\\Amenagements" but no such service exists.');
    }
}
