<?php

namespace ContainerL9p09Mq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCfKDs1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RCfKDs1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RCfKDs1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'amenagement' => ['privates', '.errored..service_locator.RCfKDs1.App\\Entity\\Amenagements', NULL, 'Cannot autowire service ".service_locator.RCfKDs1": it references class "App\\Entity\\Amenagements" but no such service exists.'],
        ], [
            'amenagement' => 'App\\Entity\\Amenagements',
        ]);
    }
}
