<?php

namespace ContainerKlbQebH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIrh9qFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bIrh9qF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bIrh9qF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'archi' => ['privates', '.errored..service_locator.bIrh9qF.App\\Entity\\Amenagements', NULL, 'Cannot autowire service ".service_locator.bIrh9qF": it references class "App\\Entity\\Amenagements" but no such service exists.'],
        ], [
            'archi' => 'App\\Entity\\Amenagements',
        ]);
    }
}
