<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRtzp7y3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRtzp7y3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRtzp7y3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRtzp7y3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRtzp7y3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rtzp7y3',
    'container.build_id' => 'd44ca26c',
    'container.build_time' => 1608217426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRtzp7y3');
