<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJ4Dvl7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJ4Dvl7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWJ4Dvl7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWJ4Dvl7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWJ4Dvl7\App_KernelDevDebugContainer([
    'container.build_hash' => 'WJ4Dvl7',
    'container.build_id' => 'a8652868',
    'container.build_time' => 1608545442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJ4Dvl7');
